### ISSUE TITLE
[URLFollow] skip links that are the same as the previous link

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot#1]
_From @StarlitGhost on December 10, 2013 10:31_

Maybe on a timer, so if it's posted 15 minutes later it will follow it again.

_Copied from original issue: StarlitGhost/PyMoronBot#25_

**Comment by TyranicMoron** [comment]
At the time this was more relevant, but people are pretty good about checking first these days. And it's not a big deal if it happens anyway.

So, closing as wontfix.
