### ISSUE TITLE
Port over comic module

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot#101]
Reference: https://github.com/ckingdev/weedbotv2/blob/master/ComicGenerator.py

Should be able to specify how many lines back the starting line for the comic is.

**Comment by StarlitGhost** [comment]
Or give some of the line you want to start with, like your OOC module.

**Comment by Heufneutje** [comment]
Probably a better idea yeah.

**Comment by HubbeKing** [comment]
Ported over now, thanks @lunik1! We wanna do a new issue for improvements or no?

**Comment by lunik1** [comment]
Yeah, what did you have in mind specifically?

**Comment by HubbeKing** [comment]
Could use some debug-logging to show what images were used, there's one background image currently that's acting up a bit...

**Comment by Heufneutje** [comment]
This has been implemented and fixed.
