### ISSUE TITLE
Port PyHeufyBot's relevant modules

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot#138]
### Utility

- [x] UserLocation
- [x] GeoLocation
  - Replace GPSLookup with this.

### Commands

- [x] Chatmap
- [x] Commands
- [x] Log
  - ~~Just needs the PHP stuff.~~ up at https://logs.dbco.link
- [x] LogSearch
- [x] OpenWeatherMap
- [x] OutOfContext
  - Just needs the conversion tool as the module itself will be part of a generic list module.
- [x] Tell
  - Encode PM tells.
- [x] Time
  - Look for an alternative since Google wants money for it now.

~~- Event~~ Scrapped due to becoming obsolete.
~~- NowPlaying~~ Scrapped due to becoming obsolete.

**Comment by Heufneutje** [comment]
_StarlitGhost commented on May 29, 2018_

Obfuscating tells in the database would be nice, could be as simple as base64 encoding.We can't fully encrypt stuff because there are no user accounts or passwords (and I don't think we want there to be), but I'd rather not read people's PM tells if I'm looking at that table for some reason. And if we're encoding PM tells we might as well do them all.

**Comment by HubbeKing** [comment]
OOC might need some work, as the List module doesn't (yet?) have a message buffer for adding the way OOC does.

**Comment by HubbeKing** [comment]
We can probably use google's Time Zone API for time for now, since there's $200/month of free credit per google API SKU. Since we're not doing anything else with the Time Zone SKU, that's 40,000  calls each month before we'd have to pay for it.

See: https://developers.google.com/maps/billing/understanding-cost-of-use#billing-overview

**Comment by HubbeKing** [comment]
Is it worth looking into logging and lastsaid/lastsaw as well?

**Comment by Heufneutje** [comment]
We already have logging. All we would need is the PHP stuff. The log searching I can port.

**Comment by StarlitGhost** [comment]
The Log module has been updated to match PyHeufyBot format, and the logs are online at https://logs.dbco.link via https://github.com/DesertBot/DesertBot-Log

Log search stuff is still yet to be done.

**Comment by Heufneutje** [comment]
All done!
