### ISSUE TITLE
Migrate utils to util modules, called by actions

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot#14]
Allows them to be reloaded without restarting the bot.

~~[dice.py](https://github.com/DesertBot/DesertBot/blob/master/desertbot/utils/dice.py) especially~~, but maybe also ~~[api_keys.py](https://github.com/DesertBot/DesertBot/blob/master/desertbot/utils/api_keys.py)~~ and [string.py](https://github.com/DesertBot/DesertBot/blob/master/desertbot/utils/string.py)

~~[LRRChecker.py](https://github.com/DesertBot/DesertBot/blob/master/desertbot/utils/LRRChecker.py) should just be part of the [LRR](https://github.com/DesertBot/DesertBot/blob/master/desertbot/modules/commands/LRR.py) module, I don't know why it is still separate.~~ Done

See [WebUtils.py](https://github.com/DesertBot/DesertBot/blob/master/desertbot/modules/utils/WebUtils.py) for an example of how to do this.

**Comment by Heufneutje** [comment]
Would API keys need to exist at all if we're moving to a database system?

**Comment by HubbeKing** [comment]
No reason we couldn't store API keys in the database, it's what I do for Hubbot. A util module to add keys would be handy, and a thing to easily fetch API keys would be good.

**Comment by StarlitGhost** [comment]
I moved LRRChecker.py into the LRR module and deleted the utils file in 9fc847a021b76b5ab46e96e6619f0839efef8365.

**Comment by StarlitGhost** [comment]
string.py seems like a bad idea, but I'd still like to port the api key junk into a module

**Comment by HubbeKing** [comment]
The API keys now have a management module, which also exposes an action `apikeys-getkey` for fetching an API key by name.
https://github.com/DesertBot/DesertBot/blob/master/desertbot/modules/commands/APIKeys.py

The path to the API keys is still stored in the old file `desertbot.utils.api_keys`, but we could now migrate over existing modules to use the action to get their API keys instead, and then move the path to the API keys into the new module, and remove the old file.
Thoughts??

**Comment by StarlitGhost** [comment]
I think we're now done with this, at least for everything mentioned in my opening comment. Closing.
