### ISSUE TITLE
Travis builds sometimes fail, threading issue?

### ISSUE THREAD

**Issue by HubbeKing** [DesertBot/DesertBot#146]
Sometimes Travis builds fail with the following message:

`desertbot.modulehandler - ERROR - Python Execution Error in deferred call <twisted.python.failure.Failure builtins.FileExistsError: [Errno 17] File exists: '/home/travis/build/DesertBot/DesertBot/logs/localhost'>`

Sounds like a threading issue but I have no idea how to troubleshoot further.

**Comment by HubbeKing** [comment]
For example, see:
https://travis-ci.org/DesertBot/DesertBot/builds/525956791
https://travis-ci.org/DesertBot/DesertBot/builds/526588136

**Comment by HubbeKing** [comment]
https://travis-ci.org/DesertBot/DesertBot/builds/526747936

**Comment by Heufneutje** [comment]
This happens to me locally too. Sometimes it hangs on loading the configuration and then when it finally wakes up I get errors like these.

**Comment by HubbeKing** [comment]
The test server we use in travis fires all the commands in `test_commands.txt` at the same exact second, so that might confuse some stuff?

**Comment by StarlitGhost** [comment]
I introduced a 0.25 second delay between each command in 0468324, which seems to have fixed this.

As a bonus, all the commands and responses are now interleaved as you would expect in the Travis logs, so they're much easier to read.
