### ISSUE TITLE
[Tell] A message doesn't always fire all pending tells

### ISSUE THREAD

**Issue by HubbeKing** [DesertBot/DesertBot#166]
Something's fucky with how tells are fired.

For an example, see https://logs.dbco.link/?channel=desertbus&network=irc.dbcommunity.org&date=2019-05-17&hideevents=false&darkmode=false#line1078

I'm not entirely sure why this might be, as from what I can tell, an incoming message-channel action should cause every pending tell to be processed and thus also fired off.
https://github.com/DesertBot/DesertBot/blob/master/desertbot/modules/commands/Tell.py#L114

Threading issue, maybe? Something else pokes at Tell.py's self.tells while it's processing tells and it stops processing partway through?

**Comment by Heufneutje** [comment]
I noticed this as well. Sometimes it fires the maximum of 3, sometimes it doesn't. It worked fine when the broken tells were fixed originally.

**Comment by StarlitGhost** [comment]
It's not safe to remove elements from a list while iterating over it.
https://github.com/DesertBot/DesertBot/blob/master/desertbot/modules/commands/Tell.py#L122,#L128

Do the removes afterwards in the `for tell in chanTells:` and `for tell in pmTells:` loops, where you're not iterating over the original list.

**Comment by Heufneutje** [comment]
Possible fix in https://github.com/DesertBot/DesertBot/commit/41222f1ca7a3df1dcd7b3d8d0ddaeb9f8904eeb2

**Comment by HubbeKing** [comment]
If that does fix it, a comment as to why we're iterating over a copy would be good.

**Comment by Heufneutje** [comment]
I've seen it work properly a few times now so I'm gonna assume fixed. The comment has been added.
