### ISSUE TITLE
[Update] automatically reload affected modules

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot#18]
Should only be done when no core code is touched by commits.

Use inspect.getfile(module) in the ModuleHandler to build a map of filenames to modules, then compare & reload in Update.

Refer to [Hubbot's requirements.txt check](https://github.com/HubbeKing/Hubbot_Twisted/blob/master/hubbot/Modules/Update.py#L40) as a starting point.

**Comment by HubbeKing** [comment]
Should use inspect.getsourcefile(module), since getfile(module) would return the .pyc if one's been created.

https://docs.python.org/3/library/inspect.html#inspect.getfile
https://docs.python.org/3/library/inspect.html#inspect.getsourcefile

**Comment by HubbeKing** [comment]
Fixed in PR #19
