### ISSUE TITLE
Add a WolframAlpha function

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot#2]
_From @StarlitGhost on January 17, 2014 10:12_

http://products.wolframalpha.com/api/documentation.html

_Copied from original issue: StarlitGhost/PyMoronBot#26_

**Comment by TyranicMoron** [comment]
_From @ojii on January 17, 2014 13:46_

On the desertbus IRC I sometimes run my bot bojii which uses this: https://github.com/ojii/bottu-wolframalpha
