### ISSUE TITLE
[Update] Auto-reload improvements

### ISSUE THREAD

**Issue by HubbeKing** [DesertBot/DesertBot#20]
I realized that reloading the Update module in the middle of an update is probably gonna lead to Bad Things.

Might need to add in a thing to delay that reload until the rest of the Update process is done, so that nothing falls over.

If there was an action that reloaded a given module, we could just do all the automatic reloading through that and have it happen in a more asynchronous manner, but IDK how we'd go about that.

**Comment by Heufneutje** [comment]
I don't know that an action would help for that since that still calls a function on the module that's being reloaded. From my experience with PyHeufyBot I know that it typically doesn't go well. Maybe `reactor.callLater` on the update module reloading specifically would help?

**Comment by HubbeKing** [comment]
Should be more better now, as of a04459ef72cd0cf3a4a232830f3b17844b869117
