### ISSUE TITLE
Replace goo.gl url shortening with another service

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot#24]
Public free goo.gl is getting shut down at some point.

https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html

**Comment by HubbeKing** [comment]
Could always throw up a simple one of our own, since we've already got a server...
Something like https://yourls.org/ wouldn't be too hard to set up.

**Comment by TyranicMoron** [comment]
What URL would we want this hosted at? The domains I currently own are all a bit long.

**Comment by HubbeKing** [comment]
https://github.com/jhaals/url-shortener looks simple, and hilariously straight-forward to set up.

**Comment by StarlitGhost** [comment]
Done, we're running https://ptpb.pw at https://dbco.link

Implemented in the bot in 88507cdf7b741a95617414c9f1230560bae52780
