### ISSUE TITLE
Review the current codebase

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot#27]
The entire codebase needs to be looked over for style, documentation, and general weirdness.

If you find something that needs fixing, fix it, comment here, or make an issue, depending on the severity.
If issues are made it would be good to link them after the relevant checklist entries below (assuming you have access to edit this issue text).

- [ ] start.py
- [ ] **desertbot/**
    - [ ] channel.py
    - [ ] config.py
    - [ ] desertbot.py
    - [ ] factory.py
    - [ ] message.py
    - [ ] modulehandler.py
    - [ ] moduleinterface.py
    - [ ] response.py
    - [ ] serverinfo.py
    - [ ] user.py
    - [ ] **utils/**
        - [ ] api_keys.py
        - [ ] dice.py
        - [ ] LRRChecker.py
        - [ ] string.py
    - [ ] **modules/**
        - [ ] commandinterface.py
        - [ ] **admin/**
            - [ ] Admin.py
            - [ ] BotControl.py
            - [ ] CommandChar.py
            - [ ] Ignore.py
            - [ ] Leave.py
            - [ ] Manhole.py
            - [ ] ModuleLoader.py
            - [ ] Nick.py
            - [ ] Update.py
        - [ ] **automatic/**
            - [ ] Actions.py
            - [ ] AsterFix.py
            - [ ] Conversation.py
            - [ ] Dominotifications.py
            - [ ] Log.py
            - [ ] Responses.py
            - [ ] URLFollow.py
        - [ ] **commands/**
            - [ ] Apples.py
            - [ ] Choose.py
            - [ ] Currency.py
            - [ ] DBCalc.py
            - [ ] Dinner.py
            - [ ] Do.py
            - [ ] EightBall.py
            - [ ] Find.py
            - [ ] Flip.py
            - [ ] Gif.py
            - [ ] Googl.py
            - [ ] GPSLookup.py
            - [ ] Hangman.py
            - [ ] Help.py
            - [ ] Join.py
            - [ ] LangPlayground.py
            - [ ] LRR.py
            - [ ] Mtg.py
            - [ ] Notice.py
            - [ ] Rainbow.py
            - [ ] RedditImage.py
            - [ ] Reverse.py
            - [ ] Roll.py
            - [ ] Say.py
            - [ ] Sed.py
            - [ ] Source.py
            - [ ] Splatoon.py
            - [ ] Tango.py
            - [ ] Time.py
            - [ ] Uptime.py
            - [ ] Urban.py
        - [ ] **postprocess/**
            - [ ] AutoPasteEE.py
            - [ ] StripColour.py
        - [ ] **utils/**
            - [ ] Alias.py
            - [ ] Chain.py
            - [ ] CommandHandler.py
            - [ ] Delay.py
            - [ ] Schedule.py
            - [ ] Slurp.py
            - [ ] StringUtils.py
            - [ ] Sub.py
            - [ ] Var.py
            - [ ] WebUtils.py

Since I suspect we might need to update it, the checklist above was generated with `tree -P "*.py" -I "__pycache__|__init__.py|parsetab.py|logs|data|configs" | sed 's/├/- [/g; s/──/ ]/g; s/└/- [/g; s/│/ /g; s/ / /g'` and a little rearranging.

**Comment by Heufneutje** [comment]
So we've checked code style and rewritten the core now. And the modules have been rewritten to use actions pretty recently. Anything else that still needs to be done with this?

**Comment by StarlitGhost** [comment]
Hmm, I suppose not?

You had to look at every module for the style updates, and I did the same for the actions. And yeah, full core rewrite. We're probably good.
