### ISSUE TITLE
[URLFollow] Wikipedia-specific follow

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot#3]
_From @StarlitGhost on March 13, 2014 17:3_

title, first paragraph or so (trim like steam description)

_Copied from original issue: TyranicMoron/PyMoronBot#37_

**Comment by TyranicMoron** [comment]
https://github.com/goldsmith/Wikipedia

**Comment by StarlitGhost** [comment]
As noted in #212, https://github.com/barrust/mediawiki looks like a better, more generic library for this.
