### ISSUE TITLE
[Find] switch to a different search API

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot#50]
[Find.py](https://github.com/DesertBot/DesertBot/blob/master/desertbot/modules/commands/Find.py)

The current google one seems to have stopped producing results.

DuckDuckGo have their Instant Answers API, but nothing for full results. https://duckduckgo.com/api

Suggestions welcome.

**Comment by Heufneutje** [comment]
I just tried it and it seems to still work fine.

**Comment by Heufneutje** [comment]
According to Google's documentation the custom search API should still be up. And seeing as it currently produces results I see no reason to switch.
